AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  Perform healthchecks on private IP or private FQDN (Private Route53). Healthchecks status are pushed to Cloudwatch custom metrics.

Parameters:
  Protocol:
    Type: String
    AllowedValues: 
      - http
      - https
  Hostname:
    Type: String
  Port:
    Type: Number
  UrlPath:
    Type: String
  StringMatching:
    Type: String
  InvertHealtcheckStatus:
    Type: String
  MetricName:
    Type: String
  MetricNamespace:
    Type: String

Resources:
  AwsInternalHealthcheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Description: >-
        Perform healthchecks on private IP or private FQDN (Private Route53). 
        Healthchecks status are pushed to Cloudwatch custom metrics.
      Timeout: 10
      Policies:
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          PROTOCOL: 
            Ref: Protocol
          HOSTNAME: 
            Ref: Hostname
          PORT: 
            Ref: Port
          URL_PATH: 
            Ref: UrlPath
          STRING_MATCHING: 
            Ref: StringMatching
          INVERT_HEALTHCHECK_STATUS: 
            Ref: InvertHealtcheckStatus
          METRIC_Name: 
            Ref: MetricName
          METRIC_NAMESPACE: 
            Ref: MetricNamespace
