AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  Perform healthchecks on private IP or private FQDN (Private Route53). Healthchecks status are pushed to Cloudwatch custom metrics.

Parameters:
  Protocol:
    Type: String
    AllowedValues: 
      - http
      - https
    Description: 'Protocol of the URL to test (http or https). Default: http'
  Hostname:
    Type: String
    Description: 'Hostname or IP of the URL to test. Default: localhost'
  Port:
    Type: Number
    Description: 'Port of URL to test. Default: 80 for http, 443 for https'
  UrlPath:
    Type: String
    Description: 'Path of the URL to test. Default: no path'
  StringMatching:
    Type: String
    Description: '(Optional) String to search in the response body. If found the healcheck will succeed.'
  InvertHealtcheckStatus:
    Type: String
    Description: '(Optional) Set to true if you want to invert the healthcheck result'
  MetricName:
    Type: String
    Description: 'Name of the Cloudwatch metrics. Default: MyService'
  MetricNamespace:
    Type: String
    Description: 'Namespace of the Cloudwatch Metric. Default: HealthCheck'
  Cron: 
    Type: String
    Description: 'Cron expression (example : "0/5 * * * ? *" : run healthchecks every 5 minutes )'
  SecurityGroupIds:
    Type: List<String>
  SubnetIds:
    Type: List<String>

Resources:
  AwsInternalHealthcheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Description: >-
        Perform healthchecks on private IP or private FQDN (Private Route53). 
        Healthchecks status are pushed to Cloudwatch custom metrics.
      Timeout: 10
      Policies:
        - CloudWatchPutMetricPolicy: {}
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          PROTOCOL: 
            Ref: Protocol
          HOSTNAME: 
            Ref: Hostname
          PORT: 
            Ref: Port
          URL_PATH: 
            Ref: UrlPath
          STRING_MATCHING: 
            Ref: StringMatching
          INVERT_HEALTHCHECK_STATUS: 
            Ref: InvertHealtcheckStatus
          METRIC_Name: 
            Ref: MetricName
          METRIC_NAMESPACE: 
            Ref: MetricNamespace
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule:
              'Fn::Join':
                - ''
                - - 'cron('
                  - !Ref Cron
                  - ')'